export type TToken = {
   _id: string;
   token: string;
   tokenType: string;
   supply: number;
   decimals: number;
   mint_time: number;
   name: string;
   symbol: string;
   metadataUri: string;
   photo: string;
   description: string;
   website: string;
   x: string;
   telegram: string;
   creator: string;
   pool: string;
   hardcap: number;
   list_time: number;
   isMigrated: boolean;
   migrationPool: string | null;
   lastTradeId: string | null;
   lastTradeExecutionPositionKey: string | null;
   priceSol: number;
   priceUsd: number;
   marketCapUsd: number;
   progress: number | null;
   progressSol: number;
   _balanceSol: number;
   _balanceTokens: number;
   last_tx_time: number;
   buys: number;
   sells: number;
   txCount: number;
   holders: number;
   volumeSol: number;
   volumeUsd: number;
   isDraft: boolean;
   configAddress: string;
   createdAt: string;
   updatedAt: string;
   price: number;
   topHoldersPercentage: number;
   topHoldersList: unknown[];
   creatorSharePercentage: number;
};
